### ISSUE TITLE
Null safety and more

### ISSUE THREAD

**Issue by gmpassos** [johnpryan/shelf_gzip#7]
https://github.com/johnpryan/shelf_gzip/pull/5 adds very important features:

- Null Safety compliant.
- Optimized bytes reading and compression.
- Tests.

`shelf` is a popular package and `shelf_gzip` should be used by everybody that uses `shelf`.

If you wish you can transfer the package to someone that wants to maintain it:
https://pub.dev/policy#name-squatting

I know that sometimes we don't have extra time for our open source projects.

Best regards.

**Comment by johnpryan** [comment]
Closed in https://github.com/johnpryan/shelf_gzip/pull/5
