### ISSUE TITLE
Publish 4.0.1

### ISSUE THREAD

**Issue by gmpassos** [johnpryan/shelf_gzip#9]
Hi,

I saw that you have already merged the small adjustment:
https://github.com/johnpryan/shelf_gzip/commit/839903a90cbe588e7d6449768d70358869c0e80e

It will be great if you publish the 4.0.1 version.

Thanks.

Best regards

**Comment by gmpassos** [comment]
Hi, please. Publish a new version to https://pub.dev

Best regards.

**Comment by johnpryan** [comment]
Done, thanks for the reminder 😅
